// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0-zEI4nI0gbmj-weP69UnXCWGkzwryM',
    appId: '1:128457266349:web:63f56fc3ec593413172224',
    messagingSenderId: '128457266349',
    projectId: 'greenhouse-ctrl-system',
    authDomain: 'greenhouse-ctrl-system.firebaseapp.com',
    databaseURL: 'https://greenhouse-ctrl-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'greenhouse-ctrl-system.appspot.com',
    measurementId: 'G-Y4BXLWR3CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOHR4kL1aHMVQBjXTW5Lq8piFrJLGYPeI',
    appId: '1:128457266349:android:f4447058471350a5172224',
    messagingSenderId: '128457266349',
    projectId: 'greenhouse-ctrl-system',
    databaseURL: 'https://greenhouse-ctrl-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'greenhouse-ctrl-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKOuQGq-OkC9k5ibSdH4QmnNv5KQ8m9Dk',
    appId: '1:128457266349:ios:e83dae8dd8882f91172224',
    messagingSenderId: '128457266349',
    projectId: 'greenhouse-ctrl-system',
    databaseURL: 'https://greenhouse-ctrl-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'greenhouse-ctrl-system.appspot.com',
    iosBundleId: 'com.example.greenhouseProject',
  );
}
